DROP PROCEDURE [ti].[bancoUpsert] ;
DROP PROCEDURE [ti].[baseBancoInsert] ;
DROP PROCEDURE [ti].[baseUpsert] ;
DROP PROCEDURE [ti].[colunaFuncaoUpsert] ;
DROP PROCEDURE [ti].[colunaUpsert]
DROP PROCEDURE [ti].[funcaoUpsert]
DROP PROCEDURE [ti].[linguagemProgramaInsert]
DROP PROCEDURE [ti].[linguagemUpsert]
DROP PROCEDURE [ti].[linUpsert]
DROP PROCEDURE [ti].[objetoBaseInsert]
DROP PROCEDURE [ti].[objetoTipoObjetoInsert]
DROP PROCEDURE [ti].[objetoTipoUpsert]
DROP PROCEDURE [ti].[objetoUpsert]
DROP PROCEDURE [ti].[programaUpsert]
DROP PROCEDURE [ti].[sistemaUpsert]

DROP FUNCTION [ti].[bancoExiste]
DROP FUNCTION [ti].[bancoId]
DROP FUNCTION [ti].[baseBancoExiste]
DROP FUNCTION [ti].[baseBancoId]
DROP FUNCTION [ti].[baseExiste]
DROP FUNCTION [ti].[baseId]
DROP FUNCTION [ti].[colunaExiste]
DROP FUNCTION [ti].[colunaFuncaoExiste]
DROP FUNCTION [ti].[colunaFuncaoId]
DROP FUNCTION [ti].[colunaId]
DROP FUNCTION [ti].[colunaObjetoExiste]
DROP FUNCTION [ti].[colunaObjetoId]
DROP FUNCTION [ti].[funcaoExiste]
DROP FUNCTION [ti].[funcaoId]
DROP FUNCTION [ti].[funcaoProgramaExiste]
DROP FUNCTION [ti].[funcaoProgramaId]
DROP FUNCTION [ti].[linExiste]
DROP FUNCTION [ti].[linguagemProgramaExiste]
DROP FUNCTION [ti].[linguagemProgramaId]
DROP FUNCTION [ti].[linId]
DROP FUNCTION [ti].[objetoBaseExiste]
DROP FUNCTION [ti].[objetoBaseId]
DROP FUNCTION [ti].[objetoExiste]
DROP FUNCTION [ti].[objetoId]
DROP FUNCTION [ti].[objetoOrigemExiste]
DROP FUNCTION [ti].[objetoOrigemId]
DROP FUNCTION [ti].[objetoTipoExiste]
DROP FUNCTION [ti].[objetoTipoId]
DROP FUNCTION [ti].[objetoTipoObjetoExiste]
DROP FUNCTION [ti].[objetoTipoObjetoId]
DROP FUNCTION [ti].[programaExiste]
DROP FUNCTION [ti].[programaId]
DROP FUNCTION [ti].[sistemaExiste]
DROP FUNCTION [ti].[sistemaId]

drop table [ti].[colunasFuncoes]
drop table [ti].[objetosOrigens]

drop table [ti].[colunasObjetos]
drop table [ti].[funcoesProgramas]
drop table [ti].[basesBancos]
drop table [ti].[objetosBases]
drop table [ti].[objetosTiposObjetos]
drop table [ti].[programasSistemas]
drop table [ti].[linguagensProgramas]

drop table [ti].[bancos]
drop table [ti].[bases]
drop table [ti].[objetosTipos]
drop table [ti].[objetos]
drop table [ti].[colunas]
drop table [ti].[sistemas]
drop table [ti].[linguagens]
drop table [ti].[programas]
drop table [ti].[funcoes]
